### ISSUE TITLE
im using angualr material 

### ISSUE THREAD

**Issue by ljjolic99** [changhuixu/session-expiration-alert#10]
I get this dependencie when i npm start my angualr app
![image](https://user-images.githubusercontent.com/62387885/100006086-eded5e00-2d97-11eb-9e16-cdd382696411.png)

Do i need to add bootstrap cux im not using it

**Comment by changhuixu** [comment]
Hi @ljjolic99 
This is an issue raised in #1 
I currently don't have a good way to make it generic to all css libraries, unless I make the modal dialog+service from scratch.

I recommend you simply copy&paste my code to your project to make it adaptive to Angular Material.

Thank you.
