### ISSUE TITLE
I have implemented in Angular 10 project, not showing an alert

### ISSUE THREAD

**Issue by tussharkhairnar** [changhuixu/session-expiration-alert#9]

**Comment by tussharkhairnar** [comment]
![image](https://user-images.githubusercontent.com/33326321/92702689-21127a80-f36f-11ea-8306-3300fde13b7d.png)

![image](https://user-images.githubusercontent.com/33326321/92702830-469f8400-f36f-11ea-9ca5-695ce644af87.png)
![image](https://user-images.githubusercontent.com/33326321/92702888-5a4aea80-f36f-11ea-8f0a-a4e9648799bd.png)
![image](https://user-images.githubusercontent.com/33326321/92702931-65057f80-f36f-11ea-9946-b1fe58e9fa8b.png)

**Comment by changhuixu** [comment]
Do you still have this issue?

**Comment by changhuixu** [comment]
close this issue due to age
